name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Please describe your idea below.
  - type: dropdown
    id: module
    attributes:
      label: Module
      description: Which module does this relate to?
      options:
        - data-download-tool
        - plant-growth-module
        - Repository / CI
        - New module
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Problem or Motivation
      description: What problem does this solve, or what use case does it enable?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe your preferred approach, if you have one.
    validations:
      required: false
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other approaches you thought of?
    validations:
      required: false
