# L. Guillaumot (BRGM), June 2026

# This script allows :
# 1) importing concentration and infiltration timeseries into the HYDRUS input data file "ATMOSPH.IN"
# 2) running Hydrus with "run.bat" (os command)
# 3) importing recharge and associated concentration timeseries generated by Hydrus (output files "T_Level.out" and "solute1.ou")
# 4) initializing a MODFLOW6 model with solute transport model
# 5) running MODFLOW model step by step, calling at each time recharge and associated concentration from the Hydrus model
#    and use them as input data for the MODFLOW model
# 6) showing some results (control convergence, water and mass balance, evolution of flow, water table and concentrations)


# ======================================================================================================================
# IMPORT PACKAGES
# ======================================================================================================================

import matplotlib.pyplot as plt
import numpy as np
import matplotlib.backends.backend_pdf
import pandas as pd
import os
from datetime import datetime, timedelta
import flopy
import time  # to save the computing time
from tqdm import tqdm

from generate_atmosph import generate_atmosph  # pre-processing for HYDRUS
from modify_UZ_settings import update_soil_params
from read_hydrus_results import read_solute, read_tlevel, read_nod_inf  # to import HYDRUS results
from functions_modflow import ModFlowSimulation  # functions to run MODFLOW using the flopy library
from functions_modflow import parse_volume_budgets  # to extract water balance and error percentage from MODFLOW simulations
from functions_modflow import read_modflow_mass_budget, pivot_budget  # to extract solute mass balance and error percentage from MODFLOW simulations


# ======================================================================================================================
# HYDRUS MODEL
# ======================================================================================================================

# define the number of simulated days
nbdays = 3000  # has to be inferior to the size of input data provided to HYDRUS, equal size of input data provided to HYDRUS if not provide)

# function replacing infiltration and associated concentration in "ATMOSPH.IN" (HYDRUS input data)
input_dir = "inputs/"
hydrus_templates_dir = "hydrus_templates/"
prec_factor = 0.1  # to have infiltration rate in cm from mm
prec_factor = prec_factor * 0.7  # to reduce a bit recharge
ctop_factor = 0.001  # to have concentration in infiltration in mg/cm3 from mg/L
generate_atmosph(template_path=hydrus_templates_dir+"ATMOSPH.IN", inf_csv_path=input_dir+"inf_hydrus.csv",
                 conc_csv_path=input_dir+"conc_infiltration_hydrus.csv", output_path="ATMOSPH.IN",
                 prec_factor=prec_factor, ctop_factor=ctop_factor, nbdays=nbdays)

# HYDRUS parameters
# take care that the initial water content is between thr and ths !!!
thr = 0.02  # residual water content (no unit)
ths = 0.437  # saturated water content (no unit)
alfa = 0.138  # Parameter alfa in the soil water retention function (1/cm)
n = 0.592  # Parameter n in the soil water retention function (no unit)
ks = 504  # saturated conductivity (cm/days)
l = 1  # tortuosity parameter in the conductivity function (no unit)
out = update_soil_params(hydrus_templates_dir + "SELECTOR.IN",
                         thr=thr, ths=ths,
                         alfa=alfa, n=n,
                         ks=ks, l=l,
                         output_path="SELECTOR.IN")

# run Hydrus
print("\nRunning HYDRUS model")
start_time = time.time()
os.system(os.path.join(".", "run.bat"))  # can be deactivated if already run once to reduce computing time or debugging
print("\n  => computing time of HYDRUS : " + str(int(time.time() - start_time)) + " seconds\n")

# extract Hydrus results
print("\nImporting HYDRUS results : solute1.out and T_Level.out files")
df_s = read_solute("solute1.out")
df_t = read_tlevel("T_Level.out")

infiltration_Hydrus = -df_t["rTop"] * 10  # mm/day  (# 1 mm <=> 1 mm/m2 <=> 0.001 m3 <=> 1 L
mass_infiltration_Hydrus = df_s["cvTop"] * 10000  # mg/m2/day
conc_infiltration_Hydrus = np.where(infiltration_Hydrus == 0, 0, mass_infiltration_Hydrus / infiltration_Hydrus)  # mg/L
GW_recharge_Hydrus = -df_t["vBot"] * 10  # mm/day  (# 1 mm <=> 1 mm/m2 <=> 0.001 m3 <=> 1 L
mass_GW_recharge_Hydrus = -df_s["cvBot"] * 10000  # mg/m2
conc_GW_recharge_Hydrus = mass_GW_recharge_Hydrus / GW_recharge_Hydrus  # mg/L


# ======================================================================================================================
# MODFLOW6 MODEL
# ======================================================================================================================

# The MODFLOW model also contains the solute transport model
# MODFLOW model units are in day and meter
timestep = 1  # day

class groundwater_modflow:

    def initial(self):
        self.model_name = "GWMODEL"

        # MODFLOW MODEL GEOMETRY
        self.nlay = 1
        self.nrow = 200
        self.ncol = 100
        domain_width = 2000  # m
        domain_length = 1000  # m
        self.delr = domain_width / self.nrow
        self.delc = domain_length / self.ncol
        # modelled domain
        self.idomain = np.ones((self.nlay, self.nrow, self.ncol), dtype=int)  # 1 active cell, else 0

        self.charge_amont_imposee = 100  # m
        self.slope = 0.003  # gradient hydraulique
        self.aquifr_thickness = 16  # m
        self.topo_elevation = 6  # depth of the imposed head compared to the surface altitude

        # defining top and bottom of the aquifer layer
        self.top = np.zeros((self.nrow, self.ncol))
        self.botm = np.zeros((self.nrow, self.ncol))
        for ir in range(self.nrow):
            for ic in range(self.ncol):
                self.top[ir, ic] = self.topo_elevation + self.charge_amont_imposee - ir * self.delr * self.slope  # ainsi la topo est X m au dessus de la charge imposée
                self.botm[ir, ic] = self.topo_elevation + self.charge_amont_imposee - ir * self.delr * self.slope - self.aquifr_thickness

        # initial hydraulic head condition
        strt_head = self.idomain * 1.0  # niveau initial en mNGF
        for ir in range(self.nrow):
            for ic in range(self.ncol):
                strt_head[0, ir, :] = self.charge_amont_imposee - ir * self.delr * self.slope

        # hydrodynamic parameters (constant value or (nlay, nrow, ncol) 3D-array
        hk = 1e-3 * 24 * 3600  # m/day
        sy = 0.15  # specific yield

        # initializing the ModFlow6 model
        self.modflow_directory_output = "."  # it seems that it does not work well if we run the model in another folder => to check
        self.ndays = len(df_t)  # equal the length of the HYDRUS timeserie
        print("\nInitializing MODFLOW6 model")
        self.modflow = ModFlowSimulation(self.model_name,
                                         self.modflow_directory_output, path_mf6dll='modflow',
                                         ndays=self.ndays, timestep=timestep,
                                         specific_storage=1e-7, specific_yield=sy,
                                         nlay=self.nlay,  nrow=self.nrow, ncol=self.ncol,
                                         rowsize=self.delr, colsize=self.delc,
                                         top=self.top, bottom=self.botm,
                                         basin=self.idomain, head=strt_head,
                                         permeability=hk,
                                         north_chd=self.charge_amont_imposee, slope=self.slope,
                                         width=self.aquifr_thickness,
                                         verbose=False)

    def dynamic(self):

        # sim_head = np.zeros((((self.ndays, self.nlay, self.nrow, self.ncol)))) * np.nan  # simulated head will be saved in a 4D array : time, layer, row, col
        # Budget_ModFlow_error = np.zeros(self.ndays) * np.nan  # will contain water mass balance error for each MODFLOW stress period

        print("\nRunning MODFLOW6 model step by step")
        for tt in tqdm(range(self.ndays)):  # For each timestep
            # print("Simulation time : ", tt)
            # give recharge rate to MODFLOW for this timestep, for each MODFLOW cell
            groundwater_recharge_modflow = np.where(self.idomain[0] == 1, -df_t["vBot"][tt] / 100 * self.delr * self.delc, 0)  # has to be in m3/day !!! curious because it should be in m/day
            self.modflow.set_recharge(groundwater_recharge_modflow)
            # give concentration in the recharge to MODFLOW for this timestep, for each MODFLOW cell
            gw_conc_recharge_modflow = np.where(self.idomain[0] == 1, 0,0)

            input_conc = conc_GW_recharge_Hydrus[tt] * 1.0  # mg/L
            gw_conc_recharge_modflow[19, 60] = input_conc * self.delr * self.delc * 10  # do not know why but we need to multiply by area and by 10 !!!

            # exemple of adding a concentration in the recharge at specific time and at specific location
            # if tt >= 10:
            #     input_conc = 15  # mg/L
            #     gw_conc_recharge_modflow[19, 60] = input_conc * self.delr * self.delc * 10 # do not know why but we need to multiply by area and by 10 !!!

            self.modflow.set_conc_recharge(gw_conc_recharge_modflow)

            # running MODFLOW for this timestep
            self.modflow.step()

            # extracting the new simulated hydraulic head map
            # sim_head[tt] = np.reshape(self.modflow.head.astype(np.float32), (self.nrow, self.ncol))

            # Check the water balance in the aquifer: recharge = capillary + baseflow + storage change + imposed head - imposed head
            # le plus simple sera d'aller lire le fichier de bilan de masse de MODFLOW (cf. fonctions d'Augustin)
            # mf_list = flopy.utils.MfListBudget(os.path.join(self.modflow_directory_output, self.model_name + ".lst"))
            # incremental, cumulative = mf_list.get_dataframes()
            # sim = flopy.mf6.MFSimulation.load(sim_ws=self.modflow_directory_output, verbosity_level=0)
            # gw = sim.get_model(self.model_name)
            # cbb = gw.output.budget()
            # cbb.get_unique_record_names(decode=True)  # pour avoir les noms de tous les champs dispos
            # cbb.list_records()
            # stor_records = cbb.get_data(kstpkper=kstpkper, text="NOM_DU_CHAMP")

            # mid_gwflow = np.nansum((groundwater_recharge_modflow) * delc * delr / 2)  # in m3/timestep, for water balance computation
            # Budget_ModFlow_error[tt] = np.round(100 * (np.nansum(
            #     (groundwater_recharge_modflow - (capillar + baseflow) * self.var.modflow_timestep -
            #      (self.var.groundwater_storage_top_layer - groundwater_storage_top_layer0)) * self.var.modflow_cell_area) / mid_gwflow),
            #                                 2)

        self.modflow.finalize()

# Initializing and running the MODFLOW6 model
start_time = time.time()
gwf_model = groundwater_modflow()
gwf_model.initial()
gwf_model.dynamic()
print("\n  => computing time of MODFLOW : " + str(int(time.time() - start_time)) + " seconds")
print("  => computing time of MODFLOW : " + str(int(time.time() - start_time) / gwf_model.ndays) + " seconds per day of simulation\n")

# ======================================================================================================================
# EXTRACTING RESULTS OF THE COUPLED MODEL
# ======================================================================================================================
print("\nExtracting HYDRUS and MODFLOW results")

# Defining figures size
plt.rcParams["figure.figsize"] = (12, 9)

# Defining model dates
first_date = '01/01/1960'
last_date = '31/12/2019'
nb_modelstep = ((datetime.strptime(last_date, "%d/%m/%Y") - datetime.strptime(first_date, "%d/%m/%Y")) / timestep).days + 1

dates_model = []
dates_model.append(datetime.strptime(first_date, "%d/%m/%Y"))
current_date = datetime.strptime(first_date, "%d/%m/%Y")
while current_date != datetime.strptime(last_date, "%d/%m/%Y"):
    current_date = dates_model[-1] + timedelta(days=1)
    dates_model.append(current_date)
dates_model = dates_model[:gwf_model.ndays]

# Importing MODFLOW global water balance
df = parse_volume_budgets(os.path.join("", gwf_model.model_name + ".lst"))  # cumulative water balance
rch_modflow = df["RCH_IN"].values
chd_in_modflow = df["CHD_IN"].values
chd_out_modflow = df["CHD_OUT"].values
stoss_in_modflow = df["STO-SS_IN"].values
stosy_in_modflow = df["STO-SY_IN"].values
stoss_out_modflow = df["STO-SS_OUT"].values
stosy_out_modflow = df["STO-SY_OUT"].values
# to switch from cumulative to step by step flow
rch_modflow[1:] = df["RCH_IN"].values[1:] - df["RCH_IN"].values[:-1]
chd_in_modflow[1:] = df["CHD_IN"].values[1:] - df["CHD_IN"].values[:-1]
chd_out_modflow[1:] = df["CHD_OUT"].values[1:] - df["CHD_OUT"].values[:-1]
stoss_in_modflow[1:] = df["STO-SS_IN"].values[1:] - df["STO-SS_IN"].values[:-1]
stosy_in_modflow[1:] = df["STO-SY_IN"].values[1:] - df["STO-SY_IN"].values[:-1]
stoss_out_modflow[1:] = df["STO-SS_OUT"].values[1:] - df["STO-SS_OUT"].values[:-1]
stosy_out_modflow[1:] = df["STO-SY_OUT"].values[1:] - df["STO-SY_OUT"].values[:-1]

total_in = rch_modflow + chd_in_modflow + stoss_in_modflow + stosy_in_modflow
total_out = chd_out_modflow + stoss_out_modflow + stosy_out_modflow
percent_error = 100.0 * (total_in - total_out) / ((total_in + total_out) / 2)

# Display MODFLOW error percentage
plt.figure()
plt.plot(percent_error)
plt.title("Discrepancy percentage of the MODFLOW model (flow model)", fontsize=16)
plt.ylabel("Discrepancy percentage (%)", fontsize=16)
plt.xlabel("Simulation time (d)", fontsize=16)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.grid()

# Display recharge calculated from HYDRUS and recharge imposed to MODFLOW
plt.figure()
plt.plot(-df_t["vBot"] / 100 * 1000, lw=2.5, label="total recharge from the HYDRUS column")
plt.plot(rch_modflow / (2000*1000-1000*20) * 1000, lw=1.5, label="total recharge actually imposed to MODFLOW")  # (2000*1000-1000*20) because recharge is not imposed in imposed head cell
plt.title(" Groundwater recharge", fontsize=16)
plt.ylabel("Recharge rate (mm/d)", fontsize=16)
plt.xlabel("Simulation time (d)", fontsize=16)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.grid()
plt.legend()


lst_file_path = gwf_model.model_name + "_T" + ".lst"  # Replace with your .lst file path
df = read_modflow_mass_budget(lst_file_path)
wide = pivot_budget(df)

# Display MODFLOW error percentage for the mass of solute
plt.figure()
# if the input concentration is very small and if there is not yet solute in the GW model,
# it can generates very small solute concentrations and potentially high discrepancy error, but it is not problematic
threshold_error_display = 10-9  # MODFLOW units i.e. mg/day
raw_error_transp = wide['PERCENT_DISCREPANCY_N/A'] * 1.0
raw_error_transp[(wide['TOTAL_IN_IN'] + wide['TOTAL_OUT_OUT']) / 2 < threshold_error_display] = 0
plt.plot(raw_error_transp)
plt.title("Discrepancy percentage of the MODFLOW model (solute transport model)", fontsize=16)
plt.ylabel("Discrepancy percentage (%)", fontsize=16)
plt.xlabel("Simulation time (d)", fontsize=16)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.grid()

# Display recharge calculated from HYDRUS and recharge imposed to MODFLOW

imposed_conc = wide['RCH_IN'] / (10*10) / (rch_modflow / (2000*1000-1000*20) * 1000)  # mg/L (1mm/m2=0.001m3=1L)

plt.figure()
plt.plot(conc_GW_recharge_Hydrus, lw=2.5, label="concentration in the recharge from the HYDRUS column")
plt.plot(imposed_conc, lw=1.5, label="concentration actually imposed into MODFLOW recharge")  # (2000*1000-1000*20) because recharge is not imposed in imposed head cell
plt.title(" Groundwater recharge concentration (mg/L)", fontsize=16)
plt.ylabel("Concentration (mg/L)", fontsize=16)
plt.xlabel("Simulation time (d)", fontsize=16)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.grid()
plt.legend()


# Display results

# Display infiltration imposed at the top of the HYDRUS column and gw recharge simulated at the bottom of the HYDRUS column
plt.figure()
plt.plot(dates_model, -df_t["rTop"] * 10, label="imposed infiltration")
plt.plot(dates_model, -df_t["vBot"] * 10, label="simulated recharge")
plt.grid()
plt.legend(fontsize=14)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.xlabel('Simulation time', fontsize=16)
plt.ylabel('Flow rate (mm/day)', fontsize=16)

# same plot at monthly scale
df_t_monthly = df_t * 1.0
df_t_monthly.index = dates_model
df_t_monthly = df_t_monthly.resample('ME').sum()
plt.figure()
plt.plot(df_t_monthly.index, -df_t_monthly["rTop"] * 10, label="imposed infiltration")
plt.plot(df_t_monthly.index, -df_t_monthly["vBot"] * 10, label="simulated recharge")
plt.grid()
plt.legend(fontsize=14)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.xlabel('Simulation time (month)', fontsize=16)
plt.ylabel('Flow rate (mm/month)', fontsize=16)


# Display concentration in the infiltration imposed at the top of the HYDRUS column and in the gw recharge simulated at the bottom of the HYDRUS column
plt.figure()
plt.plot(dates_model, conc_infiltration_Hydrus, lw=2.5, c="royalblue",
         label="concentration in the infiltration imposed to HYDRUS")
plt.plot(dates_model, conc_GW_recharge_Hydrus, lw=1.5, c="orange", linestyle='--',
         label="concentration in the recharge simulated by HYDRUS")
plt.grid()
plt.legend(fontsize=12)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.xlabel('Simulation time', fontsize=16)
plt.ylabel('Solute concentration (mg/L)', fontsize=16)

# Display cumulative injected mass and cumulative mass stored in the GW model
plt.figure()
plt.plot(mass_GW_recharge_Hydrus * gwf_model.delr * gwf_model.delc, lw=2.5, c="royalblue",
         label="mass in the recharge simulated by HYDRUS")  # mg /m2 * 100m2
# plt.plot(wide['STORAGE-AQUEOUS_OUT'] - wide['STORAGE-AQUEOUS_IN'], lw=1, c="orange", linestyle='-',
#          label="mass stored in the GW model")  #mg
plt.plot(wide['STORAGE-AQUEOUS_OUT'] - wide['STORAGE-AQUEOUS_IN'] + wide['CHD_OUT'], lw=1, c="orange", linestyle='-',
         label="mass stored in the GW model or leaving the system")
plt.grid()
plt.legend(fontsize=12)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.xlabel('Simulation time', fontsize=16)
plt.ylabel('Solute mass (mg)', fontsize=16)


# Extract and plot hydraulic heads
headobj = flopy.utils.binaryfile.HeadFile(gwf_model.model_name + ".hds")
times = headobj.get_times()  # simulation stress period
head = headobj.get_alldata()
head = np.squeeze(head, axis=1)  # because we have only one layer in the MODFLOW model => head is now a 3D-array (time, row, col)

# loading the simulation in order to have all required information to plot model results using flopy options
sim_out = flopy.mf6.MFSimulation.load(sim_name=gwf_model.model_name, sim_ws="", verbosity_level=0)
gwf = sim_out.get_model()

# Plot settings
vmin_head = np.nanmin(head[head > -1e29])  # for the colorbar
vmax_head = np.nanmax(head[head < 1e29])  # for the colorbar
time_display = [0, 365, int(365.25*5)]    # choosing to display only several time steps
time_display = [815, 851, 1095]

f = plt.figure(figsize=(17, 8))

for it in range(len(time_display)):  # for several chosen time steps
    ax = plt.subplot(1, 3, it+1)
    pmv = flopy.plot.PlotMapView(model=gwf, layer=0, ax=ax)
    ax.set_aspect("equal")
    # plot simulated head in map
    pmv.plot_array(head[time_display[it]].flatten(), cmap="viridis", vmin=vmin_head, vmax=vmax_head)
    pmv.plot_grid(colors="k", alpha=0.1)
    ax.set_title(f"Stress period {time_display[it]}\n", fontsize=12)
    # plot simulated head in map : iso-piezometric levels
    pmv.contour_array(head[time_display[it]], levels=np.arange(vmin_head, vmax_head + 1, 1), cmap="Reds", linewidths=1,
                      vmin=vmin_head, vmax=vmax_head)
    cb = f.colorbar(pmv.ax.collections[0], ax=ax, shrink=0.8)#, orientation="horizontal")
    # cb.tick_params(labelsize=12, size=0)
    cb.set_label("Hydraulic head (m)", fontsize=12)
    # display CHD Boundary conditions :
    pmv.plot_bc("CHD", color="grey")

    ax.set_title(str(int(time_display[it]-789)) + " days after the end of the injection\n")

plt.tight_layout()

# Display hydraulic head time variations at several points
y_pz = [100, 500, 1000, 1500, 1900]  # y location of the fictive piezometers (in meter)
row_pz = np.array([int(pz/gwf_model.delr) for pz in y_pz])  # associated row number
col_pz = 50  # x location of the fictive piezometers (col number)
top_pz = gwf_model.topo_elevation + 100 - row_pz * 10 * 0.003  # altitude of the surface at each piezometer, in order to compute water table depth
plt.figure()
for pz in range(len(y_pz)):
    plt.plot(dates_model, head[:, row_pz[pz], col_pz], label="Y piezometer : " + str(y_pz[pz]) + " m")
plt.xlabel("Simulation time", fontsize=16)
plt.ylabel("Simulated water table (m)", fontsize=16)
plt.grid()
plt.legend(fontsize=14)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)

plt.figure()
for pz in range(len(y_pz)):
    plt.plot(dates_model, head[:, row_pz[pz], col_pz] - top_pz[pz],
             label="Y piezometer : " + str(y_pz[pz]) + " m")
plt.xlabel("Simulation time", fontsize=16)
plt.ylabel("Simulated water table depth (m)", fontsize=16)
plt.grid()
plt.legend(fontsize=14)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)

plt.figure()
y = np.arange(0 + gwf_model.delr / 2, gwf_model.delr * gwf_model.nrow, gwf_model.delr)
top = gwf_model.topo_elevation + gwf_model.charge_amont_imposee - y * gwf_model.slope
plt.plot(y, top, 'k', label="model top")
plt.plot(y, np.mean(head[:, :, col_pz], 0), label="time-averaged simulated water table")
plt.xlabel("Y (m)", fontsize=16)
plt.ylabel("Altitude (m)", fontsize=16)
plt.grid()
plt.legend(fontsize=14)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)


# Extract and display groundwater transport convergence


# Extract and display concentrations
conc_sim = gwf_model.modflow.gwt.output.concentration().get_alldata()
conc_sim = np.squeeze(conc_sim, axis=1)  # because we have only one layer in the MODFLOW model => conc_sim is now a 3D-array (time, row, col)
#  /1000 to convert from mg/m3 to mg/L ???

# Display concentration in map
vmin_conc = np.nanmin(conc_sim)  # for the colorbar
vmax_conc = np.nanmax(conc_sim)  # for the colorbar
f = plt.figure(figsize=(17, 8))
for it in range(len(time_display)):  # for several chosen time steps
    ax = plt.subplot(1, 3, it+1)
    pmv = flopy.plot.PlotMapView(model=gwf, layer=0, ax=ax)
    ax.set_aspect("equal")
    # plot simulated concentration
    conc_display = conc_sim[time_display[it]].flatten()
    conc_display = np.where(conc_display < 1e-9, np.nan, np.log10(conc_display))
    pmv.plot_array(conc_display, cmap="viridis")#, vmin=vmin_conc, vmax=vmax_conc)
    pmv.plot_grid(colors="k", alpha=0.1)
    ax.set_title(f"Stress period {time_display[it]}\n", fontsize=12)
    # pmv.contour_array(conc_sim[time_display[it]], levels=np.arange(vmin_conc, vmax_conc + 1, 1), cmap="Reds", linewidths=1,
    #                   vmin=vmin_conc, vmax=vmax_conc)
    cb = f.colorbar(pmv.ax.collections[0], ax=ax, shrink=0.8)#, orientation="horizontal")
    # cb.tick_params(labelsize=12, size=0)
    cb.set_label("log10(concentration) (mg/L)", fontsize=12)
    # display CHD Boundary conditions :
    pmv.plot_bc("CHD", color="grey")

    ax.set_title(str(int(time_display[it] - 789)) + " days after the end of the injection\n", fontsize=14)
    f.suptitle('Concentration in groundwater\n', fontsize=16)
plt.tight_layout()

f = plt.figure(figsize=(17, 8))
for it in range(len(time_display)):  # for several chosen time steps
    ax = plt.subplot(1, 3, it+1)
    pmv = flopy.plot.PlotMapView(model=gwf, layer=0, ax=ax)
    ax.set_aspect("equal")
    # plot simulated concentration
    conc_display = conc_sim[time_display[it]].flatten()
    conc_display = np.where(conc_display < 1e-9, np.nan, conc_display)
    pmv.plot_array(conc_display, cmap="viridis")#, vmin=vmin_conc, vmax=vmax_conc)
    pmv.plot_grid(colors="k", alpha=0.1)
    ax.set_title(f"Stress period {time_display[it]}\n", fontsize=12)
    # pmv.contour_array(conc_sim[time_display[it]], levels=np.arange(vmin_conc, vmax_conc + 1, 1), cmap="Reds", linewidths=1,
    #                   vmin=vmin_conc, vmax=vmax_conc)
    cb = f.colorbar(pmv.ax.collections[0], ax=ax, shrink=0.8)#, orientation="horizontal")
    # cb.tick_params(labelsize=12, size=0)
    cb.set_label("concentration (mg/L)", fontsize=12)
    # display CHD Boundary conditions :
    pmv.plot_bc("CHD", color="grey")

    ax.set_title(str(int(time_display[it] - 789)) + " days after the end of the injection\n", fontsize=14)
    f.suptitle('Concentration in groundwater\n', fontsize=16)
plt.tight_layout()

# Display concentration in function of time
plt.figure()
y_pz = [200, 220, 250, 300]    # y location of the fictive piezometers (in meter)
row_pz = np.array([int(pz/10) - 1 for pz in y_pz])  # associated row number
col_pz = [60, 60, 60, 60]  # x location of the fictive piezometers (col number)
for pz in range(len(y_pz)):
    plt.plot(dates_model, conc_sim[:, row_pz[pz], col_pz[pz]], label="distance from the injection : " + str(y_pz[pz]-y_pz[0]) + " m")
plt.xlabel("Simulation time", fontsize=16)
plt.ylabel("Concentration (mg/L)", fontsize=16)
plt.title("Evolution of the concentration at several location\n", fontsize=16)
plt.grid()
plt.legend(fontsize=14)
plt.yticks(fontsize=14)
plt.xticks(fontsize=14)
plt.legend(fontsize=14)


## Save all figures
pdf = matplotlib.backends.backend_pdf.PdfPages("Results_coupledmodels.pdf")
for fig in range(1, plt.figure().number):
    pdf.savefig(fig)
pdf.close()

plt.close('all')  # close all figures














